### ISSUE TITLE
"baud detect failed"

### ISSUE THREAD

**Issue by leozlee** [deeplyembeddedWP/cc2640r2f-sbl-linux#1]
I get this error,I want to know how to detect if I enter the bootloader mode? I erase the flash using SmartRF Flash Programmer2,but I still get the same return! could u please tell me how to debug the device?BTW, my device is cc2640r2f
thx

**Comment by vinay-divakar** [comment]
Have you enabled and configured the bootloader settings in the .ccfg file? It will fail if the bootloader is not enabled and configured properly.

**Comment by leozlee** [comment]
Somehow , I use another device and it work. Thanks
