### ISSUE TITLE
Convert files

### ISSUE THREAD

**Issue by ystartgo** [deeplyembeddedWP/cc2640r2f-sbl-linux#2]
"Convert the .hex to .bin using the hex2bin python application."
Can more clear what files Convert the .hex to .bin using the hex2bin?
I want to use in openwrt

**Comment by deeplyembeddedWP** [comment]
The compiled firmware file is output in hex format. The serial bootloader expects you to input the firmware in binary format. So, you convert it from. hex to bin format.

**Comment by vinay-divakar** [comment]
The compiled firmware file is output in hex format. The serial bootloader expects you to input the firmware in binary format. So, you convert it from. hex to bin format.
